CREATE TABLE APPLICATION_CONFIG_1 (
		FIELD_KEY VARCHAR(255) NOT NULL,
		FIELD_VALUE VARCHAR(255) NOT NULL,
		FIELD_EXPIRE NUMERIC(15 , 0)
	);

ALTER TABLE APPLICATION_CONFIG_1 ADD CONSTRAINT APP_CFG_1_PK PRIMARY KEY (FIELD_KEY);

CREATE TABLE APPLICATION_CONFIG_2 (
		FIELD_KEY NUMERIC NOT NULL,
		FIELD_VALUE DATE NOT NULL,
		FIELD_EXPIRE NUMERIC(15 , 0)
	);

ALTER TABLE APPLICATION_CONFIG_2 ADD CONSTRAINT APP_CFG_2_PK PRIMARY KEY (FIELD_KEY);