INSERT INTO APPLICATION_CONFIG_1 (FIELD_KEY, FIELD_VALUE) VALUES ('app.name', 'calculator');
INSERT INTO APPLICATION_CONFIG_1 (FIELD_KEY, FIELD_VALUE) VALUES ('app.version', '1.0.0');

INSERT INTO APPLICATION_CONFIG_2 (FIELD_KEY, FIELD_VALUE) VALUES (1, '1978-01-01');
INSERT INTO APPLICATION_CONFIG_2 (FIELD_KEY, FIELD_VALUE) VALUES (2, '1978-01-02');