CREATE TABLE CONTACT (
		ID NUMERIC(5, 0) NOT NULL,
		CONTACT_TYPE NUMERIC(3, 0) NOT NULL,
		CONTACT_VALUE VARCHAR(25) NOT NULL
	);

CREATE TABLE PERSON (
		ID NUMERIC(5, 0) NOT NULL,
		NAME VARCHAR(25) NOT NULL,
		DATE_OF_BIRTH DATE,
		PICTURE BLOB(1024),
		PASSWORD NUMERIC(5, 0) NOT NULL,
		COLOR VARCHAR(25),
		SPEED NUMERIC(5, 0)
	);

CREATE TABLE USER_CONTACT (
		CONTACT NUMERIC(5, 0) NOT NULL,
		PERSON NUMERIC(5, 0) NOT NULL
	);

CREATE TABLE CONTACT_TYPE (
		ID NUMERIC(3, 0) NOT NULL,
		NAME VARCHAR(25) NOT NULL
	);

CREATE TABLE PERSON_FRIEND (
		PERSON NUMERIC(5, 0) NOT NULL,
		FRIEND NUMERIC(5, 0) NOT NULL
	);

ALTER TABLE CONTACT_TYPE ADD CONSTRAINT CONTACT_TYPE_PK PRIMARY KEY (ID);

ALTER TABLE PERSON ADD CONSTRAINT USER_PK PRIMARY KEY (ID);

ALTER TABLE CONTACT ADD CONSTRAINT CONTACT_PK PRIMARY KEY (ID);

ALTER TABLE USER_CONTACT ADD CONSTRAINT USER_CONTACT_PK PRIMARY KEY (CONTACT, PERSON);

ALTER TABLE PERSON_FRIEND ADD CONSTRAINT USER_FRIEND_PK PRIMARY KEY (PERSON, FRIEND);

ALTER TABLE USER_CONTACT ADD CONSTRAINT PER_CCT_CCT_FK FOREIGN KEY (CONTACT)
	REFERENCES CONTACT (ID)
	ON DELETE CASCADE;

ALTER TABLE PERSON_FRIEND ADD CONSTRAINT PER_FRD_PER_FK1 FOREIGN KEY (PERSON)
	REFERENCES PERSON (ID)
	ON DELETE CASCADE;

ALTER TABLE PERSON_FRIEND ADD CONSTRAINT PER_FRD_PER_FK2 FOREIGN KEY (FRIEND)
	REFERENCES PERSON (ID)
	ON DELETE CASCADE;

ALTER TABLE CONTACT ADD CONSTRAINT CCT_CCT_TYPE_FK FOREIGN KEY (CONTACT_TYPE)
	REFERENCES CONTACT_TYPE (ID)
	ON DELETE RESTRICT;

ALTER TABLE USER_CONTACT ADD CONSTRAINT PER_CCT_PER_FK FOREIGN KEY (PERSON)
	REFERENCES PERSON (ID)
	ON DELETE CASCADE;

